### PR TITLE
Support grpc-web-text format

### LINKED ISSUE #37: Flask example
Hi,

Do you have an example of this with Flask?

Thank you!

### PR DESCRIPTION
**Pull request by public**
This is the default mode in grpc-web.

Will need to fix up the CI to actually work properly with this.

Fixes #37

### CODE REVIEW

**Comment by gitpushdashf** [comment]
Wow, this is huge. Thank you!

**Comment by public** [comment]
@gitpushdashf tests pass, any chance you could checkout this PR and give it a go for me? :)

**Comment by gitpushdashf** [comment]
Thank you!

```
grpc-web-python-example % git diff
diff --git a/requirements.txt b/requirements.txt
index 26ed00f..ac9b5f1 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,6 @@
 flask==1.1.2
-sonora==0.1.1
+# sonora==0.1.1
+git+https://github.com/public/sonora.git@grpc-web-text#egg=sonora
 grpcio-tools
 mypy-protobuf
 flake8==3.9.0
```

This is working for me with Firefox. Can't see any issues with it so far at all. Looks good to me.

**Comment by public** [comment]
Great, I will try and do a release this week.

**Pull request merged**
